-- Learn topics + tools catalog + tool picker tasks, seeded from
-- src/data/learn.ts, src/data/tools.ts, src/data/toolTasks.ts.
-- learn_topics is seeded before tools since tools.learn_slug references it.

create table if not exists public.learn_topics (
  slug text primary key,
  title text not null,
  category text not null check (category in ('Foundations', 'Tools')),
  summary text not null,
  read_time text not null,
  tags text[] not null default '{}',
  sections jsonb not null default '[]',
  key_takeaways text[] not null default '{}',
  related_tool_slugs text[]
);

create table if not exists public.tools (
  id text primary key,
  name text not null,
  maker text not null,
  best_for text[] not null default '{}',
  description text not null,
  strengths text[] not null default '{}',
  limitations text[] not null default '{}',
  pricing_note text not null,
  learn_slug text references public.learn_topics (slug)
);

-- recommended_tool_ids references public.tools.id conceptually, but is kept
-- as a plain text[] rather than a strict foreign key since Postgres can't
-- FK-constrain individual elements of an array column.
create table if not exists public.tool_tasks (
  id text primary key,
  label text not null,
  keywords text[] not null default '{}',
  recommended_tool_ids text[] not null default '{}',
  reasoning text not null
);

-- ─────────────────────────────
-- Row Level Security
-- ─────────────────────────────
alter table public.learn_topics enable row level security;
alter table public.tools enable row level security;
alter table public.tool_tasks enable row level security;

create policy "Public can read learn topics"
  on public.learn_topics for select
  using (true);

create policy "Public can read tools"
  on public.tools for select
  using (true);

create policy "Public can read tool tasks"
  on public.tool_tasks for select
  using (true);

-- ─────────────────────────────
-- Seed data
-- ─────────────────────────────
insert into public.learn_topics (slug, title, category, summary, read_time, tags, sections, key_takeaways, related_tool_slugs)
values
  ('what-is-generative-ai', 'What Is Generative AI?', 'Foundations', 'The basics of generative AI: how it differs from traditional software, and why it matters for professional work.', '4 min', array['Basics', 'Concepts'], '[{"heading":"The short version","body":["Generative AI refers to models that produce new content — text, code, images, audio — rather than simply retrieving or classifying existing data. Traditional software follows rules you write explicitly; generative AI learns patterns from vast amounts of data and uses them to predict what comes next.","In a work context, this means you can describe an outcome in plain language and get a draft, summary, analysis, or piece of code back — instead of building that output by hand from scratch."]},{"heading":"Why it''s different from search","body":["A search engine finds existing documents that match your query. A generative AI model synthesizes a new answer by combining patterns it learned during training. That makes it powerful for drafting and reasoning, but it also means outputs can be confidently wrong — they are predictions, not lookups."]},{"heading":"Where it fits in daily work","body":["Most professional use cases fall into a few buckets: drafting and rewriting text, summarizing long content, answering questions about a document or codebase, analyzing data, and generating first-pass code or designs. The common thread is that AI produces a strong starting point — a human still reviews and finalizes the result."]}]'::jsonb, array['Generative AI creates new content by predicting patterns, it doesn''t retrieve stored answers.', 'Treat outputs as a first draft, not a final answer — verification is part of the workflow.', 'The biggest wins come from drafting, summarizing, and analyzing — not full automation.'], null),
  ('how-llms-work', 'How Large Language Models Work', 'Foundations', 'A practical, non-technical explanation of how large language models (LLMs) like Claude and ChatGPT generate text.', '5 min', array['Basics', 'Concepts'], '[{"heading":"Prediction, not understanding","body":["A large language model (LLM) is trained on huge volumes of text to predict the next most likely word (technically, ''token'') given everything before it. It repeats this one prediction at a time to generate a full response. There is no internal database of facts being queried — the model''s ''knowledge'' is encoded as statistical patterns in its parameters."]},{"heading":"Context window","body":["Every model has a ''context window'' — the amount of text it can consider at once, including your prompt, any pasted documents, and the conversation history. Larger context windows let you paste in whole reports, transcripts, or codebases and ask questions across all of it in one go."]},{"heading":"Why models ''hallucinate''","body":["Because the model is predicting plausible text rather than looking up verified facts, it can generate statements that sound confident but are incorrect — especially for very specific, obscure, or recent information. This is why fact-checking outputs against a source (or asking the model to cite one) matters for anything you plan to rely on."]}]'::jsonb, array['LLMs generate text by predicting likely continuations, not by retrieving verified facts.', 'The context window determines how much information the model can reason over at once.', 'Always verify specific facts, figures, and citations before relying on them.'], null),
  ('prompt-engineering-basics', 'Prompt Engineering Basics', 'Foundations', 'How to write clear, effective prompts for Claude and ChatGPT that get you better results, faster.', '6 min', array['Prompting', 'Skills'], '[{"heading":"Give context, not just instructions","body":["The single biggest lever for quality output is context. Instead of ''write a project update'', tell the model who the audience is, what happened this week, what tone to use, and how long the result should be. The more relevant context you supply, the less the model has to guess."]},{"heading":"Structure your prompt","body":["A reliable pattern: (1) Role — who should the AI act as; (2) Task — what you want done; (3) Context — background, data, constraints; (4) Format — how the output should look (bullet points, table, email, code block); (5) Examples — a sample of the style or structure you want, if helpful."]},{"heading":"Iterate instead of restarting","body":["Treat the first response as a draft. Ask follow-up questions like ''make this more concise'', ''rewrite for a non-technical audience'', or ''add a section on risks'' rather than starting a new conversation from scratch — the model retains context from earlier in the thread."]}]'::jsonb, array['Context is the highest-leverage part of any prompt.', 'Use Role → Task → Context → Format as a reliable structure.', 'Refine through follow-up turns instead of rewriting from zero.'], null),
  ('responsible-ai-at-work', 'Using AI Responsibly at Work', 'Foundations', 'Practical guardrails for data privacy, accuracy, and responsible AI use in a professional setting.', '5 min', array['Governance', 'Best practice'], '[{"heading":"Know what you can share","body":["Before pasting anything into an AI tool, check your organization''s data policy. Customer personal data, confidential financials, and unreleased product details typically should not go into consumer-tier AI tools unless your company has an approved enterprise agreement in place."]},{"heading":"Verify before you rely","body":["Treat AI-generated numbers, quotes, citations, and legal or compliance statements as unverified until checked against a primary source. This is especially important for anything customer-facing, financial, or regulatory."]},{"heading":"Disclose meaningful use","body":["If AI materially shaped a deliverable — a report, code, or customer communication — it''s good practice to note it was AI-assisted, particularly in regulated or client-facing contexts, so reviewers know to check it accordingly."]}]'::jsonb, array['Never paste confidential or customer data into a tool without an approved enterprise agreement.', 'Verify facts, figures, and citations — don''t treat AI output as a source of truth.', 'Be transparent when AI meaningfully contributed to a deliverable.'], null),
  ('choosing-the-right-tool', 'Choosing the Right AI Tool for the Job', 'Foundations', 'A simple framework for matching a work task to the AI tool most likely to do it well.', '4 min', array['Strategy', 'Tools'], '[{"heading":"Match the tool to the task shape","body":["Writing and reasoning tasks over long documents favor assistants with large context windows, like Claude. Quick brainstorming, image generation, or plugin-driven tasks often favor ChatGPT. In-editor coding favors GitHub Copilot. Research needing citations favors Perplexity. Work already living in your team''s docs favors Notion AI."]},{"heading":"Consider where the work already lives","body":["The best tool is often the one embedded closest to where you already work — an AI feature inside your IDE, notes app, or CRM will usually save more time than switching to a separate chat window, even if the underlying model is similar."]},{"heading":"Try the Tool Picker","body":["This platform''s Tool Picker lets you describe a task in plain language and get a ranked shortlist of tools with reasoning — use it as a starting point, then confirm against your team''s approved tool list."]}]'::jsonb, array['Match tool choice to task shape: long-document reasoning, quick brainstorming, in-editor coding, cited research, or embedded workspace AI.', 'The most convenient tool is often the one built into where you already work.', 'Use the Tool Picker for a fast, reasoned first recommendation.'], null),
  ('understanding-claude', 'Understanding Claude', 'Tools', 'What Claude, Anthropic''s AI assistant, is best at, and how to get the most from it at work.', '4 min', array['Claude', 'Anthropic'], '[{"heading":"What it is","body":["Claude is Anthropic''s AI assistant, built with an emphasis on careful reasoning, safety, and handling long documents well. It''s a strong general-purpose choice for writing, analysis, and coding."]},{"heading":"When to reach for it","body":["Use Claude when you need to work across a large document or codebase in one conversation, want controllable and natural writing tone, or need step-by-step reasoning you can follow and check."]},{"heading":"Tips","body":["Paste full documents rather than summarizing them yourself first — Claude''s context window is designed for this. Ask it to show its reasoning for complex analysis so you can spot-check the logic."]}]'::jsonb, array['Best for long-document analysis, writing, and coding.', 'Large context window means you can paste full source material directly.', 'Ask for step-by-step reasoning on complex tasks to make outputs easier to verify.'], array['claude']),
  ('understanding-chatgpt', 'Understanding ChatGPT', 'Tools', 'What ChatGPT, OpenAI''s AI assistant, is best at, and how to get the most from it at work.', '4 min', array['ChatGPT', 'OpenAI'], '[{"heading":"What it is","body":["ChatGPT is OpenAI''s general-purpose assistant, widely adopted with a large ecosystem of custom GPTs, plugins, image generation, and voice interaction."]},{"heading":"When to reach for it","body":["Good for everyday brainstorming, quick Q&A, image generation, and tasks where a purpose-built custom GPT already exists for your workflow."]},{"heading":"Tips","body":["Be explicit about tone and format — ChatGPT responds well to direct style instructions (''write like a concise engineering update, no fluff''). Explore custom GPTs your organization has published before building a prompt from scratch."]}]'::jsonb, array['Best for brainstorming, general Q&A, and image generation.', 'Large plugin/custom-GPT ecosystem can shortcut repetitive workflows.', 'Give explicit tone and format instructions for best results.'], array['chatgpt']),
  ('understanding-notion-ai', 'Understanding Notion AI', 'Tools', 'How Notion AI, embedded in your notes and docs, can save time on everyday knowledge work.', '3 min', array['Notion', 'Docs'], '[{"heading":"What it is","body":["Notion AI is built directly into Notion pages and databases, so you can summarize, draft, or ask questions about content without leaving your workspace."]},{"heading":"When to reach for it","body":["Ideal for summarizing meeting notes, drafting first passes of project docs, and answering questions across pages your team has already written."]},{"heading":"Tips","body":["Use it right after a meeting to turn raw notes into a structured summary with action items, rather than writing the summary manually."]}]'::jsonb, array['Best when your team''s knowledge already lives in Notion.', 'Strong for meeting note summarization and first-draft docs.', 'Less suited to complex, open-ended reasoning than a dedicated assistant.'], array['notion-ai']),
  ('understanding-copilot', 'Understanding GitHub Copilot', 'Tools', 'How GitHub Copilot, an in-editor AI pair programmer, changes day-to-day engineering work.', '4 min', array['Copilot', 'Engineering'], '[{"heading":"What it is","body":["GitHub Copilot is an AI pair programmer built into your IDE, offering inline code completions and a chat mode aware of your open files and repository."]},{"heading":"When to reach for it","body":["Great for boilerplate, unit tests, refactors, and explaining unfamiliar code in a repo you''ve just joined."]},{"heading":"Tips","body":["Write a clear comment describing the function you want before letting it suggest code — the quality of suggestions tracks the quality of your intent signal. Always review generated code the same way you''d review a colleague''s PR."]}]'::jsonb, array['Best for in-editor code completion, tests, and refactors.', 'Suggestion quality improves with clear comments and function signatures.', 'Generated code still requires the same review rigor as human-written code.'], array['github-copilot']),
  ('understanding-perplexity', 'Understanding Perplexity', 'Tools', 'Using Perplexity, an AI research tool that cites its sources, for fast, trustworthy research.', '3 min', array['Perplexity', 'Research'], '[{"heading":"What it is","body":["Perplexity is an AI answer engine that searches the live web and returns a synthesized answer with citations you can click through to verify."]},{"heading":"When to reach for it","body":["Best for market research, competitor scans, and any question where you need current information with traceable sources."]},{"heading":"Tips","body":["Always open at least one or two cited sources for anything you plan to put in a report — citations reflect what the model referenced, not a guarantee of accuracy."]}]'::jsonb, array['Best for cited, up-to-date research.', 'Citations make claims easy to verify — use that feature.', 'Less suited to long creative or technical writing.'], array['perplexity']),
  ('understanding-midjourney', 'Understanding Midjourney', 'Tools', 'Generating professional-quality visuals with Midjourney, a leading AI image generation tool.', '3 min', array['Midjourney', 'Design'], '[{"heading":"What it is","body":["Midjourney is an image-generation tool known for high visual quality, popular for marketing imagery, concept art, and mood boards."]},{"heading":"When to reach for it","body":["Use it for exploratory creative visuals — campaign concepts, illustrative graphics, and mood boards — rather than pixel-precise brand assets."]},{"heading":"Tips","body":["Be descriptive about style, lighting, and composition, not just subject matter. Generate several variations and iterate rather than expecting the first result to be final."]}]'::jsonb, array['Best for concept art, marketing visuals, and mood boards.', 'Describe style and composition, not just subject.', 'Treat outputs as creative exploration, not final brand-locked assets.'], array['midjourney'])
on conflict (slug) do nothing;

insert into public.tools (id, name, maker, best_for, description, strengths, limitations, pricing_note, learn_slug)
values
  ('claude', 'Claude', 'Anthropic', array['Long-document analysis', 'Writing & editing', 'Coding', 'Careful reasoning'], 'A conversational AI assistant built for careful reasoning, long-context analysis, and trustworthy writing. Strong at working with large documents and codebases in a single conversation.', array['Very large context window — good for pasting whole documents or codebases', 'Strong, controllable writing style and tone', 'Reliable step-by-step reasoning and code generation', 'Artifacts/canvas-style outputs for drafts, code, and docs'], array['No native image generation', 'Knowledge cutoff means very recent events may be missing'], 'Free tier available; paid plans unlock higher usage limits and priority access.', 'understanding-claude'),
  ('chatgpt', 'ChatGPT', 'OpenAI', array['Brainstorming', 'General Q&A', 'Image generation', 'Plugins/integrations'], 'A widely-adopted general-purpose assistant with a large plugin/GPT ecosystem, voice mode, and built-in image generation.', array['Broad ecosystem of custom GPTs and integrations', 'Built-in image generation and data analysis tools', 'Voice mode for hands-free use', 'Fast responses for everyday tasks'], array['Style and tone can require more prompting to control precisely', 'Context window is smaller than some competitors on lower tiers'], 'Free tier available; Plus/Team plans add advanced tools and higher limits.', 'understanding-chatgpt'),
  ('notion-ai', 'Notion AI', 'Notion', array['Notes summarization', 'Docs & wikis', 'Meeting notes', 'Task drafting'], 'AI features embedded directly inside Notion docs and databases — summarizing, drafting, and translating content where your team already keeps its knowledge base.', array['Works inline with existing docs, wikis, and project trackers', 'Good for summarizing meeting notes and long pages', 'Q&A across your connected workspace content'], array['Only useful if your team already lives in Notion', 'Less capable than dedicated chat assistants for complex reasoning'], 'Add-on priced per member on top of a Notion workspace plan.', 'understanding-notion-ai'),
  ('github-copilot', 'GitHub Copilot', 'GitHub / Microsoft', array['Code completion', 'Unit tests', 'Refactoring', 'IDE workflows'], 'An AI pair programmer embedded directly in the IDE, offering inline completions, chat, and PR summaries tied to your actual codebase.', array['Inline suggestions as you type, in the editor you already use', 'Chat mode understands open files and repo context', 'Good at boilerplate, tests, and repetitive refactors'], array['Best value is realized inside a supported IDE, not as a standalone chat tool', 'Can produce plausible-looking but incorrect code — review is still required'], 'Paid per-seat subscription; often provided via a company GitHub org.', 'understanding-copilot'),
  ('perplexity', 'Perplexity', 'Perplexity AI', array['Research', 'Cited web answers', 'Market/competitor scans'], 'An AI answer engine that searches the live web and returns cited, sourced summaries — useful when you need up-to-date facts with references.', array['Answers include clickable source citations', 'Good for fast research and fact-checking', 'Handles current events and recent releases well'], array['Less suited to long creative or technical writing tasks', 'Quality depends on the quality of indexed sources'], 'Free tier available; Pro plan adds more searches and file uploads.', 'understanding-perplexity'),
  ('midjourney', 'Midjourney', 'Midjourney Inc.', array['Concept art', 'Marketing visuals', 'Mood boards'], 'A leading image-generation tool for producing highly stylized visuals from text prompts, popular for marketing, concept art, and creative exploration.', array['High visual quality and strong stylistic control', 'Large prompt community and reference styles'], array['No native text/document capability — image generation only', 'Precise text-in-image rendering is still inconsistent'], 'Subscription tiers based on monthly generation volume.', 'understanding-midjourney')
on conflict (id) do nothing;

insert into public.tool_tasks (id, label, keywords, recommended_tool_ids, reasoning)
values
  ('write-emails', 'Write or reply to emails', array['email', 'reply', 'inbox', 'message', 'correspondence'], array['claude', 'chatgpt'], 'Email drafting is a writing-and-tone task. Claude and ChatGPT both handle this well — Claude is a strong pick when you want to paste a full email thread for context.'),
  ('summarize-documents', 'Summarize long documents or reports', array['summarize', 'summarise', 'summary', 'long document', 'report', 'condense', 'tl;dr'], array['claude', 'notion-ai'], 'Summarization benefits from a large context window so the whole document can be considered at once. Claude excels here; Notion AI is the faster option if the doc already lives in Notion.'),
  ('analyse-data', 'Analyse data or spreadsheets', array['data', 'analyse', 'analyze', 'spreadsheet', 'csv', 'numbers', 'trends', 'statistics'], array['chatgpt', 'claude'], 'ChatGPT''s built-in data analysis tools are convenient for quick spreadsheet work. Claude is a strong alternative when you need to reason carefully about what the data means, not just compute it.'),
  ('generate-code', 'Generate or refactor code', array['code', 'function', 'bug', 'refactor', 'programming', 'script', 'api', 'developer'], array['github-copilot', 'claude'], 'GitHub Copilot works directly in your IDE with full repo context, making it the fastest option for day-to-day coding. Claude is a great complement for larger design discussions or reviewing a whole module at once.'),
  ('write-tests', 'Write unit tests', array['unit test', 'test coverage', 'testing', 'test cases', 'qa'], array['github-copilot', 'claude'], 'Copilot can generate tests inline against your actual function signatures. Claude is useful for reasoning through edge cases before you write the tests.'),
  ('research-market', 'Research competitors or markets', array['research', 'competitor', 'market', 'industry', 'landscape', 'trends report'], array['perplexity', 'chatgpt'], 'Perplexity searches the live web and cites sources, which matters for anything research-based that needs to be verifiable.'),
  ('create-visuals', 'Create marketing visuals or concept art', array['image', 'visual', 'design', 'artwork', 'graphic', 'illustration', 'mood board', 'creative'], array['midjourney', 'chatgpt'], 'Midjourney produces the highest visual quality for stylized creative work. ChatGPT''s built-in image generation is a fast alternative for quick, simple visuals.'),
  ('meeting-notes', 'Turn meeting notes into a summary', array['meeting', 'notes', 'minutes', 'action items', 'recap'], array['notion-ai', 'claude'], 'If your notes already live in Notion, Notion AI can summarize and extract action items without leaving the page. Claude is a strong option for messier or longer transcripts.'),
  ('customer-support', 'Draft customer support responses', array['customer', 'support', 'ticket', 'complaint', 'response', 'help desk'], array['claude', 'chatgpt'], 'Support replies need a consistent, empathetic tone at speed. Both Claude and ChatGPT handle this well — Claude is especially good at holding a consistent voice across many replies.'),
  ('presentations', 'Draft slides or presentation outlines', array['presentation', 'slides', 'deck', 'powerpoint', 'pitch'], array['chatgpt', 'claude'], 'Both assistants are strong at structuring a narrative and outline. Use either to draft the outline and talking points, then build the visual deck separately.'),
  ('hr-policy', 'Draft HR policies or people documents', array['hr', 'policy', 'people', 'handbook', 'onboarding', 'employee'], array['claude', 'notion-ai'], 'Policy writing benefits from careful, consistent language and the ability to review a full existing handbook for consistency — a strength of Claude''s long context window.'),
  ('leadership-comms', 'Write leadership or all-hands communications', array['leadership', 'all-hands', 'announcement', 'town hall', 'strategy memo', 'exec'], array['claude', 'chatgpt'], 'Leadership communication needs a controlled, consistent tone across a sensitive message — an area where Claude''s writing style control is particularly strong.')
on conflict (id) do nothing;
